### PR TITLE
Add `pytest-cov` to check coverage when running tests

### LINKED ISSUE #119: Add coverage reports using `pytest-cov`
We would want to know how much part of the code is tested.

### PR DESCRIPTION
**Pull request by aitorres**
Closes #119 

## What I did

- [x] Added `pytest-cov` as a dev-dependency for the project, on `pyproject.toml` (and updated the `.lock` file as well)
- [x] Modified the default options / parameters for `pytest` to include coverage checks

I verified that by running `pytest` locally, I got the output of the coverage report. 

Other things I could add to this PR:

- Set a minimum coverage percentage, if needed
- Report lines that are missing from coverage, instead of just each file's coverage percent 

## How to test

You should be able to get the report locally by `poetry install`ing the new dependency and then running `pytest`.

Note that I'm not 100% sure if something else needs to be done in the `main.yml` workflow file, or if it'll use the `pyproject.toml`'s config automatically when running `pytest`.

Let me know if there's anything else I should change!

### CODE REVIEW

**Comment by aitorres** [comment]
I solved the merge conflicts with `master`, I think that should also solve the issue with `black` on the Github Actions pipeline for this branch. Will keep an eye on the PR just in case

**Comment by gridhead** [comment]
@onuralpszr, Could you please take a look at this?

**Comment by onuralpszr** [comment]
```
platform linux -- Python 3.10.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/user/Github/naiff, configfile: pyproject.toml
plugins: flake8-1.1.0, isort-2.0.0, black-0.3.12, cov-4.0.0
collected 78 items                                                                                                 

nvautoinstall/__init__.py sss                                                                                [  3%]
nvautoinstall/main.py ...                                                                                    [  7%]
nvautoinstall/decoration/__init__.py sss                                                                     [ 11%]
nvautoinstall/decoration/status.py sss                                                                       [ 15%]
nvautoinstall/interfaces/__init__.py sss                                                                     [ 19%]
nvautoinstall/interfaces/check_superuser_permissions.py sss                                                  [ 23%]
nvautoinstall/interfaces/handle_compatibility_check.py sss                                                   [ 26%]
nvautoinstall/interfaces/handle_drivers_installation.py sss                                                  [ 30%]
nvautoinstall/interfaces/handle_prime_support.py sss                                                         [ 34%]
nvautoinstall/interfaces/handle_rpmfusion_repositories.py sss                                                [ 38%]
nvautoinstall/interfaces/install_cuda_support.py sss                                                         [ 42%]
nvautoinstall/interfaces/install_everything.py sss                                                           [ 46%]
nvautoinstall/interfaces/install_ffmpeg_support.py sss                                                       [ 50%]
nvautoinstall/interfaces/install_nvidia_repositories.py sss                                                  [ 53%]
nvautoinstall/interfaces/install_video_acceleration.py sss                                                   [ 57%]
nvautoinstall/interfaces/install_vulkan_support.py sss                                                       [ 61%]
nvautoinstall/operations/__init__.py sss                                                                     [ 65%]
nvautoinstall/operations/check_superuser_permissions.py sss                                                  [ 69%]
nvautoinstall/operations/handle_compatibility_check.py sss                                                   [ 73%]
nvautoinstall/operations/handle_cuda_installation.py sss                                                     [ 76%]
nvautoinstall/operations/handle_drivers_installation.py sss                                                  [ 80%]
nvautoinstall/operations/handle_prime_support.py sss                                                         [ 84%]
nvautoinstall/operations/handle_rpmfusion_repositories.py sss                                                [ 88%]
nvautoinstall/operations/install_ffmpeg_support.py sss                                                       [ 92%]
nvautoinstall/operations/install_video_acceleration.py sss                                                   [ 96%]
nvautoinstall/operations/install_vulkan_support.py sss                                                       [100%]

---------- coverage: platform linux, python 3.10.7-final-0 -----------
Name                                                        Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------------------
nvautoinstall/__init__.py                                      12      0   100%
nvautoinstall/decoration/__init__.py                            1      0   100%
nvautoinstall/decoration/status.py                             16      5    69%   30, 34, 38, 42, 46
nvautoinstall/interfaces/__init__.py                           11      0   100%
nvautoinstall/interfaces/check_superuser_permissions.py        12      8    33%   27-35
nvautoinstall/interfaces/handle_compatibility_check.py         37     33    11%   27-62
nvautoinstall/interfaces/handle_drivers_installation.py        38     34    11%   36-82
nvautoinstall/interfaces/handle_prime_support.py               54     49     9%   39-104
nvautoinstall/interfaces/handle_rpmfusion_repositories.py      29     25    14%   35-71
nvautoinstall/interfaces/install_cuda_support.py               52     48     8%   37-112
nvautoinstall/interfaces/install_everything.py                 13      9    31%   27-36
nvautoinstall/interfaces/install_ffmpeg_support.py             37     33    11%   37-84
nvautoinstall/interfaces/install_nvidia_repositories.py        44     40     9%   35-110
nvautoinstall/interfaces/install_video_acceleration.py         37     33    11%   37-82
nvautoinstall/interfaces/install_vulkan_support.py             37     33    11%   37-82
nvautoinstall/main.py                                          42     42     0%   20-110
nvautoinstall/operations/__init__.py                            9      0   100%
nvautoinstall/operations/check_superuser_permissions.py         5      2    60%   25-26
nvautoinstall/operations/handle_compatibility_check.py         29     22    24%   28-47, 50-56, 59-68
nvautoinstall/operations/handle_cuda_installation.py           26     16    38%   26-31, 34-37, 40-43, 46-47, 50-51, 54-55, 58-59
nvautoinstall/operations/handle_drivers_installation.py        15     10    33%   26-29, 32-42
nvautoinstall/operations/handle_prime_support.py               15     13    13%   22-34
nvautoinstall/operations/handle_rpmfusion_repositories.py      17     11    35%   26-31, 34-35, 38-48
nvautoinstall/operations/install_ffmpeg_support.py              5      2    60%   25-26
nvautoinstall/operations/install_video_acceleration.py          5      2    60%   25-26
nvautoinstall/operations/install_vulkan_support.py              5      2    60%   25-26
-----------------------------------------------------------------------------------------
TOTAL                                                         603    472    22%


========================================== 3 passed, 75 skipped in 0.48s ===========================================


```

cc @t0xic0der  It does work but for future we need tests. For now it is LGTM

**Comment by gridhead** [comment]
> cc @t0xic0der It does work but for future we need tests. For now it is LGTM

Yeah, without tests - the coverage does not quite mean anything but I suppose I should have kept the tests issue as a dependency for this one. Should I go ahead and merge it?

**Comment by gridhead** [comment]
@aitorres Could you please resolve the merge conflicts and squash your commits to just one commit introducing the said change?

**Comment by onuralpszr** [comment]
> > cc @t0xic0der It does work but for future we need tests. For now it is LGTM
> 
> Yeah, without tests - the coverage does not quite mean anything but I suppose I should have kept the tests issue as a dependency for this one. Should I go ahead and merge it?

Honestly we need tests but for dep sake we can keep it. If become a problem we can remove it.

**Comment by onuralpszr** [comment]
@aitorres hello, do you want to take action or shall I do it ?

**Comment by onuralpszr** [comment]
Complete via https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/commit/11e81df107fe31f6612946df2be44ab2a07b3efd

**Pull request closed without merging**
