### PR TITLE
RPM Packaging

### PR DESCRIPTION
**Pull request by lcts**
As promised. The specfile is all you really need, but I made a couple of additional changes to facilitate packaging:

- renamed to `nvautoinstall`. The full name is rather unwieldy for a package, and it is not a good idea to include F32 in the name, since this is likely to work on other versions as well. I chose your executables as a naming template, but obviously`this can be changed to whatever you like
- use setuptools to configure/install. This is a bit overkill for such a simple script, but it makes maintaining the package **much** simpler because you don't have to worry about setting up the correct paths, byte-compilation, dependencies etc. yourself

The .specfile is a pretty bog-standard Fedora/Python affair. If you dislike the above changes, one would replace the macros in the `%build` and `%install` sections with explicit commands for installation & add colorama/etc as `BuildRequires: ...`

The package installs fine & displays help when called without options. I don't have NVidia cards, so I didn't test further. There's a test build [in my copr](https://copr.fedorainfracloud.org/coprs/lcts/nvautoinstall/packages/).

### CODE REVIEW

**Comment by gridhead** [comment]
Hi @lcts! Thanks for putting in the work for packaging this and for going one more step with the additional changes - which certainly would help. Could you walk me through the process of testing the package from COPR (and also why you prefer to have all of your commit messages in lower case 😁)?

**Comment by lcts** [comment]
Edit: I made a mistake in (2) and (3), my explanation  was only true when using tito, I apparently forgot how to use rpkg. I've corrected the error.

Sure.
1. Log in at COPR using your FAS account, make a new project. Most of the stuff on the page is self-explanatory, if your project will only contain one package it makes sense to use project name = package name. Under *Build Options -> Chroots*, select all versions of Fedora/CentOS/whatever you want to build for by default, under *Other Options*, make sure *follow Fedora branching* is checked (this makes sure that your project will automatically create new repos for new Fedora versions when they're released). Hit *Create* and you'll see the newly created page for your project. (You'll find the previous settings page unter *Settings -> Project Details*, the only thing that can no longer be changed is the project name.)

2. Go to *Packages -> Create a new package*. Enter details, again most defaults are fine. *Clone URL* = your repo. In section 2 you actually tell the build system how to create your package. The default, *rpkg*, is fine, personally I tend to use tito (that's what my test build was created from, check out the `tito` branch in my fork). Both utilities basically perform the task of creating a tarball from your repo's contents and passing that tarball + the specfile on to the build system to create the package. Both offer quite powerful automation on top of that, rpkg is nice because in its simplest use it requires no modifications to your software's repo beyond it containing a spec file.

2.1. Build packages using basic rpkg
Either:
 - Tag the Release you want to build a package from, then point *Committish* at that tag [1], or
 - Create release branches from your master & point *Committish* at those branches, then **never** change them without bumping the `Release:`-value in the specfile
This is important, because otherwise, rpkg will simply build from the latest commit to master, but since it generates the package name from what is given in the specfile for `Name:`, `Version:` and `Release:` we might end up with *different* packages that have the same release version.
Before you tag/build from the release branch, make sure that the version & release given in the specfile are correct & that the changelog is updated. 

2.2. Build using tito/advanced rpkg
For more automated rpkg, check their documentation, I haven't used it in a while. With tito, I can help more directly, but their documentation is also good. Basically, the idea behind both is to automatically manage Version: and Release: fields, to generate the Changelog automatically from commit messages and, crucially, to automatically build from tags so that you don't have to manually change the Committish: whenever you want to update your package. This also allows you to make use of the auto-rebuild feature of COPR, which can e.g. automatically build new versions of your package whenever you create a tag in your git. That way, you basically never have to interact with COPR after once setting everything up.

3. Confirm, you'll see your package created but no builds yet. Hit *Rebuild*, a build will be fired off & built packages will be made available in the repo.

[1] It makes sense to name these tags according to the `Name:`, `Version:` and `Release:` values from the specfile: `<packagename>-<version>-<release>`, e.g. `nvautoinstall-0.4.0-0.3` in my test build. `<packagename>` and `<version>` are self-explanatory, `<release>` is the version number of the *package* containing the same version of the software, e.g. the third package containing 0.4.0. I usually use 0.x for pre-releases or test builds, that ensures that any actual release (<release> = 1) will override any of my test releases. This also makes it easy to deal with betas etc.: `nvautoinstall 0.4.0-beta3` would become package `nvautoinstall-0.4.0-0.x.beta3` - that way, it is clear from the package name that this is from what upstream calls `beta3`, I can create an upgrade path for betas and release candidates (`nvautoinstall-0.4.0-0.x.beta3` -> `nvautoinstall-0.4.0-0.y.rc1` with `y` > `x`), and no matter how many betas or rcs or whatever there will be, the actual release (package `nvautoinstall-0.4.0-1` will sort higher and thus override all of them. Check out the Fedora packaging guidelines for more details on this.

Further notes:
- the source URL is not really used in this scheme, but you can simply set it to whatever the URL would be if someone wanted to download the source tarball for the tag you're building from. Or set it to the name of the actual file & add a comment explaining how people can generate it
- I actually have no idea why all my commit messages are lowercase. Take your pick: using lowercase in general text makes it clear that 'Thisfile.c was rewritten' refers to a file starting with capital T and is not just grammar; as a non-native speaker I found English capitalisation rules very confusing & so didn't bother with them whenever I had an excuse not to, and the habit stuck; pure, unadulterated lazyness.

**Comment by lcts** [comment]
Addendum: I fired off a second test build using rpkg. You can check out the `builder-live.gz` build logs on [the build's page](https://copr.fedorainfracloud.org/coprs/lcts/nvautoinstall/build/1565067/) to see what copr/rpkg do with your repo in detail.

**Comment by lcts** [comment]
Sorry, my explanation in https://github.com/t0xic0der/nvidia-auto-installer-for-fedora/pull/45#issuecomment-660896500 was wrong. I've updated it, if you already read it, please re-read ...

**Comment by gridhead** [comment]
Thanks for your attention in this regard @lcts. I would certainly take a look at this and begin testing the said package as soon as it can be possible for me. Apologies for the delayed response from my end.

**Comment by lcts** [comment]
No worries, it's your project, & your time to spend.

I've written [a quick-doc](https://pagure.io/fedora-docs/quick-docs/pull-request/257) for automated Copr-publishing using tito, that might be a good fit for your project as well. It basically sets your git repository up in a way that you don't have to interact with Copr at all, it all stays in git.

The PR isn't merged, so the doc isn't on doc.fp.o yet, but you can create the page locally, as described in the quick-doc README.md.

**Comment by gridhead** [comment]
Finally, I got some time to spend on this project now that the placements headache is out of the way. I have gone through your build and there are certain questions that came up in my mind. (Now that your quick doc about COPR is merged, I can finally get documentation to refer to for information)
- Firstly, the listed requirements for the tool are `distro`, `click` and `colorama` (although I am working on a branch currently to phase out `colorama` as the functionality can be addressed by `click` so there is no need to add another dependency for it. Are you installing the binary or the script + dependencies with the package?
- Secondly, have you done packages for RPM Fusion? I mean once the COPR takes off, it would make sense to put this into RPM Fusion non-free segment as the majority of the functionality included in this tool makes use of RPM Fusion repository.

**Comment by lcts** [comment]
1) Python packaging is very automated in RPM. The dependencies are detected via setuptools' setup.py, rpmbuild automatically adds them as dependencies of the final package (unless you explicitly tell it not to):
```
% dnf repoquery --depends nvautoinstall
/usr/bin/python3
python(abi) = 3.8
python3-devel
python3-setuptools
python3.8dist(click)
python3.8dist(colorama)
python3.8dist(distro)
python3.8dist(setuptools)
```
so they'll get installed from Fedora's repositories by dnf. See [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/) for all the details regarding Python packaging in Fedora. The package itself contains both the source and the byte-compiled *.pyc stuff (Sections "Files to include" and "Byte-compiling" in the Python packaging guidelines).

2) No, only for Fedora itself, but [the process seems to be pretty much the same](https://rpmfusion.org/Contributors), they even follow Fedora's packaging guidelines. However, I wonder if it wouldn't make more sense to have it in Fedora/EPEL rather than RPMFusion? I'm not 100% on what the rules are here, but your software itself doesn't have any license/patent issues after all, and having something that - among other things - manages RPMFusion repos reside only in RPMFusion seems weird. You could ask on [Fedora's packaging list](https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/) if you're interested.

**Comment by gridhead** [comment]
Cool. That is one of the perks for having dnf written in Python in the first place so there is not much to worry about when it comes to dependencies. For now, it would be wise to stick to COPR I guess. Could you sync up the most recently created branch and version bump the package? You can find the branch [here](https://github.com/t0xic0der/nvidia-auto-installer-for-fedora/tree/v0.3.5-15-Sep-2020). 

P.S. Also one of the issues listed [here](https://github.com/t0xic0der/nvidia-auto-installer-for-fedora/issues/48) prevents me from building a binary executable for the given branch. (I believe I might just need to either wait for PyInstaller to provide support for Python 3.8 or retire the binary executables entirely to fully focus on providing a QA checked COPR package. What do you think?)

**Comment by lcts** [comment]
> Could you sync up the most recently created branch and version bump the package? You can find the branch [here](https://github.com/t0xic0der/nvidia-auto-installer-for-fedora/tree/v0.3.5-15-Sep-2020).

Done. I rebased my stuff on top of your commits.

**Comment by gridhead** [comment]
Here's the test result

```
[soumadeepdhar@PAVLO ~]$ sudo dnf copr enable lcts/nvautoinstall
[sudo] password for soumadeepdhar: 
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/lcts/nvautoinstall? [y/N]: y
Repository successfully enabled.
```

```
[soumadeepdhar@PAVLO ~]$ sudo dnf update
Copr repo for nvautoinstall owned by lcts          1.2 kB/s | 1.7 kB     00:01    
cuda-fedora29-x86_64                               2.0 kB/s | 3.0 kB     00:01    
Fedora Modular 32 - x86_64                         3.3 kB/s | 5.9 kB     00:01    
Fedora Modular 32 - x86_64 - Updates               9.9 kB/s | 5.6 kB     00:00    
Fedora 32 - x86_64 - Updates                       9.4 kB/s | 6.0 kB     00:00    
Fedora 32 - x86_64 - Updates                       158 kB/s | 2.5 MB     00:16
google-chrome                                      5.4 kB/s | 3.6 kB     00:00    
MongoDB Repository                                 1.7 kB/s | 2.5 kB     00:01    
MySQL 8.0 Community Server                         457  B/s | 2.5 kB     00:05    
MySQL Connectors Community                         4.6 kB/s | 2.5 kB     00:00    
MySQL Tools Community                              5.1 kB/s | 2.5 kB     00:00    
RPM Fusion for Fedora 32 - Nonfree - NVIDIA Dr     9.6 kB/s |  13 kB     00:01    
teams                                              4.0 kB/s | 3.0 kB     00:00    
Dependencies resolved.
```

```
[soumadeepdhar@PAVLO ~]$ sudo dnf install nvautoinstall
Last metadata expiration check: 0:00:37 ago on Wed 23 Sep 2020 07:55:48 AM IST.
Dependencies resolved.
===============================================================================
 Package          Arch   Version        Repository                        Size
===============================================================================
Installing:
 nvautoinstall    noarch 0.4.0-0.3.fc32 copr:copr.fedorainfracloud.org:lcts:nvautoinstall
                                                                         934 k
Installing dependencies:
 python3-click    noarch 7.1.1-1.fc32   updates                          145 k
 python3-colorama noarch 0.4.1-5.fc32   fedora                            33 k

Transaction Summary
===============================================================================
Install  3 Packages

Total download size: 1.1 M
Installed size: 1.8 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): python3-colorama-0.4.1-5.fc32.noarch.rp  24 kB/s |  33 kB     00:01    
(2/3): nvautoinstall-0.4.0-0.3.fc32.noarch.rpm 391 kB/s | 934 kB     00:02    
(3/3): python3-click-7.1.1-1.fc32.noarch.rpm    50 kB/s | 145 kB     00:02    
-------------------------------------------------------------------------------
Total                                          224 kB/s | 1.1 MB     00:04     
warning: /var/cache/dnf/copr:copr.fedorainfracloud.org:lcts:nvautoinstall-0a54691f872708f3/packages/nvautoinstall-0.4.0-0.3.fc32.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID d2ae9777: NOKEY
Copr repo for nvautoinstall owned by lcts      3.4 kB/s | 1.0 kB     00:00    
Importing GPG key 0xD2AE9777:
 Userid     : "lcts_nvautoinstall (None) <lcts#nvautoinstall@copr.fedorahosted.org>"
 Fingerprint: A694 3A24 1E5C 955E 6B3F 8BD6 4F51 45CF D2AE 9777
 From       : https://download.copr.fedorainfracloud.org/results/lcts/nvautoinstall/pubkey.gpg
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                       1/1 
  Installing       : python3-colorama-0.4.1-5.fc32.noarch                  1/3 
  Installing       : python3-click-7.1.1-1.fc32.noarch                     2/3 
  Installing       : nvautoinstall-0.4.0-0.3.fc32.noarch                   3/3 
  Running scriptlet: nvautoinstall-0.4.0-0.3.fc32.noarch                   3/3 
  Verifying        : nvautoinstall-0.4.0-0.3.fc32.noarch                   1/3 
  Verifying        : python3-click-7.1.1-1.fc32.noarch                     2/3 
  Verifying        : python3-colorama-0.4.1-5.fc32.noarch                  3/3 

Installed:
  nvautoinstall-0.4.0-0.3.fc32.noarch     python3-click-7.1.1-1.fc32.noarch   
  python3-colorama-0.4.1-5.fc32.noarch   

Complete!
```

```
[soumadeepdhar@PAVLO ~]$ nvautoinstall 
[ # ] NVIDIA AUTOINSTALLER FOR FEDORA 32 AND ABOVE
[ # ] OPTIONS
      --rpmadd  → This mode enables the RPM Fusion NVIDIA drivers repository.
      --driver  → This mode simply installs the NVIDIA driver.
      --x86lib  → This mode installs only the x86 libraries for Xorg.
      --nvrepo  → This mode enables the Official NVIDIA repository for CUDA.
      --plcuda  → This mode installs only the CUDA support softwares.
      --ffmpeg  → This mode installs only the FFMPEG acceleration.
      --vulkan  → This mode installs only the Vulkan renderer.
      --vidacc  → This mode installs only the VDPAU/VAAPI acceleration.
      --getall  → This mode installs all the above packages.
      --cheksu  → This mode allows you to check the user privilege level.
      --compat  → This mode allows you to check your compatibility.
      --version → Show the version and exit.
      --help    → Show this message and exit.
```

```
[soumadeepdhar@PAVLO ~]$ nvautoinstall --version
NVAutoInstFedora32 by t0xic0der, version v0.3.0
```

```
[soumadeepdhar@PAVLO ~]$ nvautoinstall --compat
[ # ] NVIDIA AUTOINSTALLER FOR FEDORA 32 AND ABOVE
[ # ] CHECKING FOR GPU COMPATIBILITY...
[ ! ] Compatibility infomation was obtained
[ ✔ ] One or more active NVIDIA GPUs were detected
      01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
      04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Picasso (rev c2)
[ ✔ ] An Optimus Dual GPU setup was detected
[ # ] GATHERING CURRENT HOST INFORMATION...
[ ! ] Host information was gathered
      System: Linux v5.8.8-200.fc32.x86_64
      Hostname: PAVLO
      Version: #1 SMP Wed Sep 9 19:31:09 UTC 2020
      Distribution: Fedora 32 x86_64
[ # ] CHECKING FOR HOST COMPATIBILITY...
[ ✔ ] Supported OS detected
      This tool is expected to work correctly here
[ ✘ ] Leaving installer
```

Works just great. Merging now.

**Review by gridhead — APPROVED** [review]
Installed the test repo and the package, then checked all the functionalities. It is working great. :+1:

**Pull request merged**
