### PR TITLE
ci: ✨ pre-commit configuration 

### LINKED ISSUE #162: [CI] Add pre-commit support for the project repository
Add pre-commit support for the project repository

### PR DESCRIPTION
**Pull request by onuralpszr**
* We have pyproject rules and everything and we can automate all of this rules withing pre-commit.ci  (https://pre-commit.ci/)

This will give us automatic checks and fixes based on the config we have inside pyproject.toml. 

How is it work ?
* Once you integrate via pre-commit.ci website, it will read the config and work on every stage (push,pr etc) that is it. 

### Other changes 
* poetry files are updated for pre-commit 
* poetry add package_name --dev deprecated (https://python-poetry.org/docs/master/managing-dependencies/)

image

* I ran pre-commit so all of the files has been fixed and send via commit  so I started first time fixed files.

### CODE REVIEW

**Comment by onuralpszr** [comment]
Pre-commit results (from my command line) 

image

**Comment by gridhead** [comment]
Fixes #162

**Review by gridhead — APPROVED** [review]
LGTM.

**Comment by onuralpszr** [comment]
It is also fixes  

https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/pull/159
https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/pull/158
https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/pull/143
https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/pull/135
https://github.com/t0xic0der/nvidia-auto-installer-for-fedora-linux/pull/134

**Pull request merged**
